services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=onlineforum_db
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres_db:5432/onlineforum_db
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      JAVA_OPTS: "-Xms512m"
    depends_on:
      - postgres_db
